name: Python CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.10'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install pytest  # Install pytest for testing
          # Add any other dependencies your project needs here, e.g.:
          # pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest test_Add.py  # Adjust the path as necessary
